# Generated by Django 4.2 on 2024-03-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storylike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storylike',
            name='story_image',
        ),
        migrations.RemoveField(
            model_name='storylike',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='StoryLike',
        ),
    ]
