# Generated by Django 4.2 on 2024-03-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_imagemessage_message_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='receiver_user',
        ),
    ]
