# Generated by Django 4.2 on 2024-03-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_rename_receiver_message_receiver_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_user',
            new_name='receiver',
        ),
    ]
