# Generated by Django 4.2 on 2024-03-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_customuser_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_public',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
