# Generated by Django 4.2 on 2024-03-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
