# Generated by Django 4.2 on 2024-03-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='file',
            field=models.FileField(null=True, upload_to='post_content/'),
        ),
    ]
